@startuml
actor Użytkownik 
participant Klient
participant Koszyk
Użytkownik -> Klient : szukaj("mleko")
activate Klient
    Klient -> Sklep : produktyDlaKategorii('mleko')
    activate Sklep
return lista_produktow
Klient -> Użytkownik : pokaz(lista_produktów)
deactivate
Użytkownik -> Klient : weź(produkt)
activate Klient
    Klient -> Sklep : wezProdukt(produkt)
    activate Sklep
    return produkt
Klient -> Koszyk : dodajProdukt(produkt)
activate Koszyk
return
Klient -> Użytkownik: "co dalej?"
deactivate 
@enduml