@startuml
allowmixing 
'elementy class można zastąpic przez object

class Pracownik
class Właściciel
class Klient
class Dostawca

'sklep jest rozumiany jako magazyn, 
'lub pomieszczenie z produktami (na półkach)
class Sklep{
    'dodanie do stanu magazynowego
    dodajProdukt(produkt:Produkt):bool
    'zdjęcie ze stanu magazynu
    wezProdukt(nazwa:String):Produkt
    'znajdź produkt dla Kateorii
    produktyDlaKategorii(kategoria): Produkt[]
}

class Koszyk
class Bank 
class "System płatności"
class Produkt{
    ' cena:float
    ' dodajKategorie():void
}
class Kategoria
class "Baza danych"

Właściciel --|> Pracownik
Pracownik o-- Dostawca
Klient -- Koszyk
Klient -- Sklep
Sklep o-- Produkt
Sklep o-- Kategoria
Produkt "kategorie" o-- "produkty" Kategoria
Pracownik -- Sklep
"System płatności"  -- Klient
"System płatności" -- Bank
Koszyk o-- Produkt
Sklep -- "Baza danych"

@enduml