@startuml

'człowiek używający aplikacji
actor Użytkownik 

'ignorujemy UI
Użytkownik -> Klient : listaProduktów("mleko")
activate Klient
Klient -> Sklep : produktyDlaKategorii("mleko")
activate Sklep
return lista_produktów
return wyświetl lista_produktów
Użytkownik -> Klient : wybrany produkt "mlekoABC"
activate Klient
Klient -> Sklep : wezProdukt("mlekoABC")
activate Sklep
return produkt
Klient -> Koszyk : dodajProdukt(produkt)
activate Koszyk
return 
Klient --> Użytkownik : "czy to koniec zakupów"
deactivate
@enduml