@startuml

(*) --> "Wejscie klienta do sklepu"
if "Klient zakończył zakupy"  as if1 then 
    --> [TAK] "Rozpoczęcie płatności"
    --> if "Wybrany typ płatności" then
        --> [Karta] "Wykładnie towar" as w1
        --> "Płatność kartą"
        --> === B1 ===
        --> "Autoryzacja w banku" 
        --> === B2 ===
        === B1 === --> "Aktualizacja stanów" 
        --> === B2 ===
        === B1 === --> "Wydruk paragonów" 
        --> === B2 ===
        --> (*)
        else 
        --> [Gotówka] "Wykładie towar" as w2 
        --> "Płatność gotówką"
        -->(*)
        else 
        --> [Kasa samoobsługowa] "Skanowanie towaru"
        --> "Płatność kartą"
    endif        
else 
    --> [NIE] "Wybór towaru z półki"
    --> "Dodanie towaru do koszyka"
    --> if1
endif


@enduml